---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: debian:jessie
    pull: true
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-"tail -f /dev/null"}
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
verifier:
  name: testinfra
  lint:
    name: flake8
