---
- name: Prepare
  hosts: all
  gather_facts: false
  pre_tasks:
  - name: Run apt-get update
    raw: apt-get update
    changed_when: false

  - name: Install python2
    raw: apt-get -y install python-simplejson
    changed_when: false

- name: Converge
  hosts: all

  vars:
    nginx_vhosts:
      - listen: "127.0.0.1:8080 default"
        server_name: "_"
        filename: "status.conf"
        extra_parameters: |
              location / {
                stub_status on;
                access_log   off;
              }
  roles:
    - role: geerlingguy.nginx
    - role: ../../
